# Generated by Django 3.1.3 on 2020-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('details', models.CharField(max_length=100, verbose_name='详细信息')),
                ('content', models.CharField(max_length=3000, verbose_name='内容')),
                ('date', models.DateField(verbose_name='日期')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
            ],
        ),
    ]
